// <auto-generated />
using System;
using ApiTicketSAG.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiTicketSAG.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("ApiTicketSAG.Models.Clientes", b =>
                {
                    b.Property<int>("codigoCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("empresa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("codigoCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ApiTicketSAG.Models.Mensaje", b =>
                {
                    b.Property<int>("idMensaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnviadoPor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensajes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("idTicket")
                        .HasColumnType("INTEGER");

                    b.HasKey("idMensaje");

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("ApiTicketSAG.Models.Tecnicos", b =>
                {
                    b.Property<int>("idEncargado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("idEncargado");

                    b.ToTable("Tecnicos");
                });

            modelBuilder.Entity("ApiTicketSAG.Models.Tickets", b =>
                {
                    b.Property<int>("idTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("asunto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("especificaciones")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("idEncargado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("solicitadoPor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("vence")
                        .HasColumnType("TEXT");

                    b.HasKey("idTicket");

                    b.ToTable("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
